# Generated by Django 5.2.3 on 2025-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('class_name', models.CharField(max_length=20)),
                ('maths_marks', models.IntegerField()),
                ('science_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
            ],
        ),
    ]
